

pipeline {

    libraries {
        lib('lib1@master')
        lib('lib2@development')
        lib('lib3@feature_branch')
    }

    agent any

    options {
        timeout(time: 1, unit: 'HOURS')
    }

    parameters {
        string(name: 'user', defaultValue: 'John', description: 'A user that triggers the pipeline')
    }

    stages {
        stage('Check pre-requirements') {
            steps {
                checkPreRequirements()
            }
        }

        stage('Build & Test') {
            parallel {
                stage('Build') {
                    steps {
                        build()
                    }
                }

                stage('Test') {
                    steps {
                        test()
                    }
                }
            }
        }
    }
}